### ISSUE TITLE
flatten includes Imports.sol

### ISSUE THREAD

**Issue by dapplion** [aragon/buidler-aragon#103]
The flatten code at code.sol includes all contracts in Import.sol where most are unrelated to the actual target Contract.

#### References
- buidler's glob to capture local contracts: https://github.com/nomiclabs/buidler/blob/64809c65da9da5eb9d8946458ec8fa8c2a7aa20c/packages/buidler-core/src/builtin-tasks/compile.ts#L73

**Comment by 0xGabi** [comment]
I think we should use the path value on `arapp.json` as the default path: https://buidler.dev/config/#path-configuration

Then users can add extra configurations on their `buidler.config.js`

**Comment by 0xGabi** [comment]
This was address with #111
