### ISSUE TITLE
Publish: update parser to @solidity-parser/parser

### ISSUE THREAD

**Issue by 0xGabi** [aragon/buidler-aragon#149]
## 🐛 Bug Report

Buidler update they parser to @solidity-parser/parser and is breaking our publishing process as we assume they have that dependency here: https://github.com/aragon/buidler-aragon/blob/master/src/utils/ast/parseContractFunctions.ts#L3

**Comment by macor161** [comment]
Related to https://spectrum.chat/aragon/app-development/unable-to-create-boilerplate-app~fcf646e8-03da-4cff-bc4a-cc61954f8108

**Comment by 0xGabi** [comment]
Yes @macor161 was solved with #150 will release a new version today
