### ISSUE TITLE
publish command does not publish correctly

### ISSUE THREAD

**Issue by macor161** [aragon/buidler-aragon#156]
## 🐛 Bug Report

Using `npx buidler publish` doesn't return any error but the repo cannot be found ounce the command is complete. Content seems to be published correctly on IPFS.

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/buidler-aragon/blob/master/CONTRIBUTING.md#ways-to-contribute)?

- [x] Yes

## To Reproduce

1. Clone `https://github.com/aragon/aragon-react-boilerplate.git`
2. Install dependencies
3. Run `npx buidler publish major --network rinkeby`

#### Environment

- macOS
- NodeJS 12

**Comment by sohkai** [comment]
Mentioned on Spectrum as well, but it appears the issue is that we are selecting the `staging` environment instead of `rinkeby` when specifying `--rinkeby` as the environment.

**Comment by 0xGabi** [comment]
Solved with #157
