### ISSUE TITLE
Running buidler with a local aragon/aragon already running

### ISSUE THREAD

**Issue by rperez89** [aragon/buidler-aragon#170]
Right now we are having the babel-plugins duplicates issue that is beign fixed here https://github.com/aragon/aragon/pull/1434.

But if you want as a workaround fix it in your local aragon/aragon start it and then start an app with buidler we get this ms `Error in plugin @aragon/buidler-aragon: Cannot start client. Port 3000 is in use.`

Before buidler we had that feature, is that possible to include it again? i a really super usefull one.

**Comment by ajsantander** [comment]
Hey @rperez89! There's an option to run the start command without the browser. Maybe that'll do what you want?

`npx buidler start --no-browser`

**Comment by rperez89** [comment]
> Hey @rperez89! There's an option to run the start command without the browser. Maybe that'll do what you want?
> 
> `npx buidler start --no-browser`

ahh yeah! thxs!

**Comment by 0xGabi** [comment]
I'll close this one as it was already addressed.
